#!/usr/bin/env bash
# Script that configures nginx on a new ubuntu machine and creates a redirection route

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
rep_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$rep_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
