#!/usr/bin/env bash
# Configures nginx in an ubuntu machine

# -y flag: Automatic yes to prompts
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y

sed -i "/listen 80 default_server/i add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo service nginx restart
