#!/usr/bin/env bash
# Configures HAproxy so that it send traffic to web-01 and web-02

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

config_str=\
"
frontend assiminee.tech-frontend
	bind *:80
	mode http
	default_backend assiminee.tech-backend

backend assiminee.tech-backend
	balance roundrobin
	server 396304-web-01 52.3.243.178:80 check
	server 396304-web-02 54.197.105.101:80 check
"

echo "$config_str" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
