#!/usr/bin/env bash
# Configures HAproxy so that it send traffic to web-01 and web-02

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

ip=$(ip addr show | grep -w inet | grep -v '127.0.0.1' | awk '{print $2}' | cut -d'/' -f1)":80"
frnt_str="errorfile 504 \/etc\/haproxy\/errors\/504.http\n\nfrontend front\n\tbind $ip\n\tdefault_backend backend_servers"
bck_str="default_backend backend_servers\n\nbackend backend_servers\n\tbalance roundrobin\n\tserver web1 52.3.243.178:80 check\n\tserver web2 54.197.105.101:80 check"

sudo sed -i "s/errorfile 504 \/etc\/haproxy\/errors\/504.http/$frnt_str/" /etc/haproxy/haproxy.cfg
sudo sed -i "s/default_backend backend_servers/$bck_str/" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
