#!/usr/bin/env bash
# Create backup for all MYSQL databases and compresses them

pwd="$1"
date=$(date +%d-%m-%Y)
mysqldump -uroot -p"$pwd" --opt --all-databases > backup.sql
tar -cvzf "$date".tar.gz backup.sql 
