#!/usr/bin/env bash
# debugging task: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx

sudo service nginx start
