#!/usr/bin/env bash
# displays /etc/passwd data in a text format
# shellcheck disable=SC2009
filename="/etc/passwd"
while read -r line
do
	IFS=: read -r -a fields <<< "$line"
	set $line
	echo "The user ${fields[0]} is part of the ${fields[3]} gang, lives in ${fields[5]} and rides ${fields[6]}. ${fields[2]}'s place is protected by the passcode ${fields[1]}, more info about the user here: ${fields[4]}"
done < $filename
