#!/usr/bin/env bash
# Edits IP addresses
facebook="8.8.8.8	facebook.com"
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo $facebook >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
